# SPDX-License-Identifier: GPL-2.0

# Makefile for DECnet ethernet endnode kernel module
obj-m += decnet3.o

decnet3-y += dnet_dev.o dnet_next.o dnet_node.o dnet_nsp.o dnet_route.o
decnet3-y += dnet_sock.o dnet_sys.o dnet_timr.o dnet_trc.o dnet.o
