.TH DNETINFO 8 "September 17 2023" "DECnet utilities"

.SH NAME
dneigh \- DECnet Neighborhood Information

.SH SYNOPSIS
.B dneigh [OPTIONS...]

.SH DESCRIPTION
.PP
.B dneigh
shows the local DECnet neighbour table in a arp like format.

.SH OPTIONS
.TP
.I "\-n"
Don't resolve node numbers into names.

.TP
.I "\-h \-\-help"
Show a help text.

.SH SEE ALSO
.BR " ip "(8)"
