.TH "dnnode" "1" "July 2024" "dnprogs" "User Commands"

.SH NAME

dnnode \- DECnet node name lookup tool

.SH SYNOPSIS

dnnode {\-h|\-\-help}

dnnode [\-v] [\-m] {nodename|nodeaddress}

.SH "DESCRIPTION"
\fBdnnode\fR is a tool that does name lookup of DECnet nodes.
It can lookup the node address from node name and node name
from node address.

.SH OPTIONS
.SS "\-v"
Be verbose. Prints useful (debug) messages.
.SS "\-\-help, \-h"
Prints a small help.

.SH SEE ALSO
\fBhost\fR(1).

.SH AUTHORS
This program is written by Philipp "ph3-der-loewe" Schafft <lion@lion.leolix.org>.
