.TH SENDVMSMAIL 8 "November 29 2023" "DECnet utilities"

.SH NAME
sendvmsmail \- mail forwarder for DECnet
.SH SYNOPSIS
.B sendvmsmail
.SH DESCRIPTION
.PP
.B sendvmsmail
Is the mail forwarding program that sends Unix mail messages to VMSmail on an OpenVMS(R)
System. It should be the default destination of the "vmsmail" user. The usual way to do this
is to create a .forward file in that user's home directory with the following contents:

| /usr/sbin/sendvmsmail

By default, sendvmsmail will use an older version of the mail-11 protocol. If
you wish to use the latest version, mail11v3, add a "-3" switch to the above
command:

| /usr/sbin/sendvmsmail -3

.SH SEE ALSO
.BR vmsmaild "(8), " dnetd "(8), " dnetd.conf "(5)
